# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  inputs:
    command: 'install'

- script: |
    npm build
  displayName: 'npm build'
- task: Npm@1
  inputs:
    command: 'install'

- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
          export SRCCLR_SCM_REF=master
          export SRCCLR_SCM_REF_TYPE=branch
          export SRCCLR_SCM_REV="$(build.buildNumber)"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --allow-dirty --update-advisor